[[ISSUERS]]
address = "rh5eaqZhAwHu2Wdzhm22yFsde9NMvGCGXG"
name = "RESET1 Test"

[[TOKENS]]
issuer = "rh5eaqZhAwHu2Wdzhm22yFsde9NMvGCGXG"
currency = "5245534554310000000000000000000000000000"
name = "RESET1 Test Token"
desc = "test launch token"
icon = "https://e92stealth.github.io/icon.png"

[[TOKENS.URLS]]
url = "https://e92stealth.github.io"
type = "website"

[[TOKENS.URLS]]
url = "https://tiktok.com/digitalreset2026"
type = "social"
